Create issue templates
Syscon-Lab/.github pull request #1
Opened 2021-11-11 11:50 UTC by imdanhye

### 작업 개요
- Syscon-Lab의 모든 repository에 적용될 issue template 생성

### 작업 분류
- [x] 공통 템플릿 작성

### 작업 상세 내용
- 각 파트 별 버그 리포트 생성(System, Motion, Perception, Localization) 및 Assinees에 파트원 할당
- 기능 개발을 위한 보편적인 템플릿 생성

### 생각해볼 문제
- Issue 이외의 협업에 필요한 템플릿에 관해 리스트업 필요 (PR template 등)
- 템플릿 내용에 관한 피드백 필요
- 추가적으로 필요한 템플릿 형식에 관한 의견

2021-11-11 11:56 UTC, Geonhee-LEE commented
@imdanhye 내용은 좋은거 같습니다. common 이슈로 모든 사람이 볼 수 있도록 template 추가가능할까요

2021-11-11 12:01 UTC, imdanhye commented
@Geonhee-LEE 넵 편리할 듯 하네요!

2021-11-11 12:16 UTC, Geonhee-LEE requested changes
이전에 feature가 아니라 enhanccement로 이야기로 되었던거 같은데, 확인 부탁드립니다!

2021-11-11 12:16 UTC, Geonhee-LEE commented on .github/ISSUE_TEMPLATE/feature_report.md
> +labels: feature
이전에 feature가 아니라 enhanccement로 이야기로 되었던거 같은데, 확인 부탁드립니다!

2021-11-11 12:19 UTC, imdanhye commented
@Geonhee-LEE @seungiloh5 
common 이슈가 추가되었습니다. 현재 모든 인원(팀장님, 연구소장님 포함)을 Assignees에 할당하였는데, 더 간편한 방법이 있다면 공유 부탁드립니다...
또한 common issue에 다른 버그 리포트와 마찬가지로 `bug` 라벨을 붙이는 게 맞을 지 / 또는 새로운 라벨이 필요할지, 의견주시면 감사하겠습니다!

2021-11-11 12:24 UTC, imdanhye commented on .github/ISSUE_TEMPLATE/feature_report.md
> +labels: feature
엇 enhancement가 공통 라벨이어서 그렇게 이야기 되었었나요? 제가 헷갈렸던 듯 싶네요.

2021-11-11 12:45 UTC, Geonhee-LEE commented on .github/ISSUE_TEMPLATE/feature_report.md
> +labels: feature
enhancement label이 저희가 말하는 새로운 개발이나 제안을 의미하는 것 같습니다 ㅎㅎ. 일단 제가 commit 했고, 이 conversation 종료하도록 하겠습니다
![image](https://user-images.githubusercontent.com/12562147/141300121-511457a6-8022-413a-8af9-549f2879ef57.png)

2021-11-11 12:46 UTC, imdanhye commented on .github/ISSUE_TEMPLATE/feature_report.md
> +labels: feature
네 확인했습니다!

2021-11-11 12:50 UTC, Geonhee-LEE commented
> @Geonhee-LEE @seungiloh5 common 이슈가 추가되었습니다. 현재 모든 인원(팀장님, 연구소장님 포함)을 Assignees에 할당하였는데, 더 간편한 방법이 있다면 공유 부탁드립니다... 또한 common issue에 다른 버그 리포트와 마찬가지로 `bug` 라벨을 붙이는 게 맞을 지 / 또는 새로운 라벨이 필요할지, 의견주시면 감사하겠습니다!

제가 생각하기에는 소장님은 제외해도 될 것 같고, 모두가 알아야하는 내용이므로 기존에 존재하는 `help wanted: Extra attention is needed(각별한 주의)`을 사용하는 것은 어떨까요

![image](https://user-images.githubusercontent.com/12562147/141300687-839c0135-3bda-41f9-ba37-ed2d09363a1e.png)

2021-11-11 12:52 UTC, Geonhee-LEE approved these changes

2021-11-11 12:55 UTC, imdanhye commented
> > @Geonhee-LEE @seungiloh5 common 이슈가 추가되었습니다. 현재 모든 인원(팀장님, 연구소장님 포함)을 Assignees에 할당하였는데, 더 간편한 방법이 있다면 공유 부탁드립니다... 또한 common issue에 다른 버그 리포트와 마찬가지로 `bug` 라벨을 붙이는 게 맞을 지 / 또는 새로운 라벨이 필요할지, 의견주시면 감사하겠습니다!
> 
> 제가 생각하기에는 소장님은 제외해도 될 것 같고, 모두가 알아야하는 내용이므로 기존에 존재하는 `help wanted: Extra attention is needed(각별한 주의)`을 사용하는 것은 어떨까요
> 
> ![image](https://user-images.githubusercontent.com/12562147/141300687-839c0135-3bda-41f9-ba37-ed2d09363a1e.png)

좋은 것 같습니다. default로 `help wanted`가 붙고, 다른 라벨은 필요 시 이슈 작성자가 추가하면 될 것 같네요!

2021-11-11 13:01 UTC, Geonhee-LEE approved these changes

2021-11-12 04:37 UTC, seungiloh5 reviewed
훌륭합니다!!
나중에라도 피드백 드릴꺼 생각하면 글 남기겠습니다!

2021-11-12 04:43 UTC, imdanhye commented
@Geonhee-LEE @seungiloh5 
건희씨 피드백 사항에 따라 PR 템플릿도 추가하였습니다. ( [협업,개발 매뉴얼 - 머지 템플릿(Merge Template)](https://www.notion.so/sysconresearch/eaeb701488f64b61afb8bee39f01449f#a0a1a0629e9147228eff8f1ad45854aa) 참조 )
확인 부탁드립니다!

2021-11-12 06:27 UTC, seungiloh5 approved these changes

2021-11-12 06:30 UTC, merged

2021-11-12 06:50 UTC, imdanhye commented
@Geonhee-LEE @seungiloh5 
Common 이슈의 Assignees에 10명 이상 할당이 불가능하여, 우선 자동으로 할당되는 인원은 팀장님과 파트장분들로 변경해놓겠습니다.